filter:
    excluded_paths: [framework/*, locale/*, docs/*, fonts/*, third_party/*, application/helpers/adodb/*, application/libraries/admin/http/*, application/libraries/admin/pclzip/*, application/extensions/*, application/views/*, application/third_party/*, images/*, styles/*, styles-public/*, templates/*, themes/*, tmp/*, upload/*]
    paths: [application/*]
checks:
    php:
        code_rating: true
        duplication: true
        one_class_per_file: true
coding_style:
    php: {  }
    
#            braces:
#            classes_functions:
#                class: new-line
#                function: new-line
#                closure: new-line